[Fix] Need to upgrade "electron-download"
Fixes the following exception:
```sh
[4/4] Building fresh packages...
error /usr/lib/secretin-app/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /usr/lib/secretin-app/node_modules/electron
Output:
Downloading SHASUMS256.txt
[============================================>] 100.0% of 2.93 kB (2.93 kB/s)
/usr/lib/secretin-app/node_modules/electron/install.js:48
  throw err
  ^

Error: Generated checksum for "electron-v1.7.8-linux-x64.zip" did not match expected checksum.
    at ChecksumMismatchError.ErrorWithFilename (/usr/lib/secretin-app/node_modules/electron-download/node_modules/sumchecker/build.js:41:124)
    at new ChecksumMismatchError (/usr/lib/secretin-app/node_modules/electron-download/node_modules/sumchecker/build.js:56:133)
    at Hash.<anonymous> (/usr/lib/secretin-app/node_modules/electron-download/node_modules/sumchecker/build.js:203:22)
    at emitNone (events.js:105:13)
    at Hash.emit (events.js:207:7)
    at emitReadable_ (_stream_readable.js:516:10)
    at emitReadable (_stream_readable.js:510:7)
    at addChunk (_stream_readable.js:277:7)
    at readableAddChunk (_stream_readable.js:253:11)
    at Hash.Readable.push (_stream_readable.js:211:10)
```